### ISSUE TITLE
Custom server address breaks other control buttons

### ISSUE THREAD

**Issue by adamzea** [timetheoretical/jitsi-meet-outlook#1]
Entering a different server address in the settings dialogue seems to break all of your other control buttons (room name, mute, video mute switches) and does not change the auto-generated meeting URL to use the new server.

![image](https://user-images.githubusercontent.com/24486391/79789735-a93ca880-8318-11ea-95b7-cfce3ac52b35.png)

As you mentioned on the [Jitsi forum](https://community.jitsi.org/t/plug-ins-for-adding-jitsi-meet-links-to-appointment-requests-emails/21564/12):

> The plug-in expects domain names without https or forwardslashes (e.g.: “gb-lon-1.jitsi.rocks” instead of “https://gb-lon-1.jitsi.rocks/”). I’ll add some checks that makes this more robust.
> The plug-in breaks if you change the domain before manually generating a random id (but if a random ID is manually generated first, a new domain name can be specified without breaking the program).

Although, I tried without the protocol and slashes as "gb-lon-1.jitsi.rocks" and that didn't seem to work properly either.

**Comment by timetheoretical** [comment]
Thanks, will look into this!

**Comment by timetheoretical** [comment]
@adamzea, in version 0.2.1, the logic behind assigning and fetching the custom domain has been reworked, and a check of the validity of the user-supplied domain is now enforced before it is assigned to the persistent preferences.

On my side, the issue you describe has disappeared. Great if you could confirm!

**Comment by adamzea** [comment]
It seems to be working very well now!  Closing.
