### ISSUE TITLE
Plug-in for Mozilla Thunderbird

### ISSUE THREAD

**Issue by semencha** [timetheoretical/jitsi-meet-outlook#16]
Hi!

Please inform, can you develop a similar plugin for mozilla thunderbird?

p/s I am ready to pay for labor, I only need an estimate of the cost.

Sincerely,
Ivan Semencha
semencha@n-kraft.ru

**Comment by timetheoretical** [comment]
Hi Ivan,

Thanks for your request, I think that its a great idea to have a similar plugin for Thunderbird.

Unfortunately, such plugins are developed in an entirely different framework, which I don't know very well.

Best of luck!

**Comment by semencha** [comment]
Thanks for the answer!

Sincerely,
Ivan Semencha
