### ISSUE TITLE
Bug installation 5.1

### ISSUE THREAD

**Issue by mfournet** [timetheoretical/jitsi-meet-outlook#18]
Hello,

Many thanks for your dev.

In installation 5.1, if you don't have visualstudio 2010 tools installed, crach installation.

**Comment by timetheoretical** [comment]
That is expected behaviour. The addon is developed within the Microsoft VSTO framework, which [according to Microsoft](https://docs.microsoft.com/en-us/visualstudio/vsto/how-to-install-the-visual-studio-tools-for-office-runtime-redistributable?view=vs-2019) requires VSTO runtime to be installed to work.

However, did earlier versions of the plug-in (pre 5.0) work for you?

**Comment by mfournet** [comment]
Yes, i have tested 0.2 and 0.4 previus it's OK . But i have installed visualstudio Tools and now is OK for 0.5.1




[http://grandbelfort.fr/logomail_lite]
Mathieu FOURNET
Directeur des Systèmes d'Information
Direction des Systèmes d'Information
mfournet@grandbelfort.fr
+33 3 70 04 80 01
+33 6 21 90 22 86



Le 7 juin 2020 16:00, timetheoretical <notifications@github.com> a écrit :

That is expected behaviour. The addon is developed within the Microsoft VSTO framework, which according to Microsoft<https://docs.microsoft.com/en-us/visualstudio/vsto/how-to-install-the-visual-studio-tools-for-office-runtime-redistributable?view=vs-2019> requires VSTO runtime to be installed to work.

However, did earlier versions of the plug-in (pre 5.0) work for you?

**Comment by timetheoretical** [comment]
Okay, thanks for letting me know. Perhaps the requirement is too strict and shouldn't be checked at install-time.

**Comment by philippe-ritter** [comment]
Hello
I got the same problem. Can you add it as dependency during the install ?
Philippe

**Comment by timetheoretical** [comment]
Okay, good to know. I will disable the check in the next release. If people then start filing issues about VSTOR not working as it is not installed I will look into a more refined solution.

**Comment by timetheoretical** [comment]
As of [v0.6.0](https://github.com/timetheoretical/jitsi-meet-outlook/releases/tag/v0.6.0), the installer no longer checks whether VSTO runtime is installed.
