### ISSUE TITLE
Possibility to pre-configure custom URL from installer ?

### ISSUE THREAD

**Issue by gillesdubois** [timetheoretical/jitsi-meet-outlook#2]
Hi @timetheoretical, 

In the first place, thanks for providing us this tool which is really appreciated.

I would like to know if its possible in a future version to implement pre-configured URL using arguments in the installer.

A common case for most of us i think is : 
- I have an on-premise installed Jitsi instance and want my users to have the outlook extension
- To have an easier installation, provide or deploy a pre-configured extension with the custom Jitsi URL already set.

Regards,
Gilles Dubois.

**Comment by timetheoretical** [comment]
Hi @gillesdubois,

I'm happy you like it!

I think this is a good idea, and from #4, it seems like many might have the same use case as you describe. I'll look into this once I have confirmed that v0.2.1 does not contain the bug described in #1 anymore, and once I have implemented some more persistent settings.

In principle, it should be possible to run the MSI installer silently via cmd. A solution to your use case could then be to supply the custom Jitsi URL as a parameter to the MSI installer in cmd. Is this along the lines you were thinking?

**Comment by gillesdubois** [comment]
Hi @timetheoretical ,

Yes that what is was thinking, something like : 
- jitsi-outlook.msi /S /URL=my.jitsi.meet.org

If i can be of any help don't hesistate to ask.

Regards,
Gilles Dubois.

**Comment by timetheoretical** [comment]
Perfect, we're on the same page then.

Thanks, I might get back to you in a couple of weeks time when I've had a look at this. It would always be useful if you could test the feature once it has been implemented.

**Comment by blinard-BIOINFO** [comment]
Hi,
Really nice outlook extension, there is great potential there.
I back previous demands for a domain pre-configured at installation. Then, creating a bat script for installation on end users computers would be easy.

**Comment by timetheoretical** [comment]
Hi both,

The [v0.4.0](../releases/tag/v0.4.0) release aims to address this issue and add the possibility to pass custom setting values to the installer as parameters in cmd. It would be great to have your feedback as to whether it works as expected. :smile:

**Comment by blinard-BIOINFO** [comment]
Thanks ! I will test that asap.

**Comment by gillesdubois** [comment]
Hi, I will also test it as soon as possible a make a feedback.

**Comment by blinard-BIOINFO** [comment]
Hi, early feedback.

Port support in domain -> works fine

**Comment by gillesdubois** [comment]
Hi,

Me and my colleagues tested this without any issues, indeed special chars doesn't work but imho its not related to the plugin but more to Jitsi itself who doesn't manage special char properly. 

Regards,
Gilles Dubois.

**Comment by fxguidet** [comment]
I can confirm that  it's working perfectly !
Outlook 2019  french.
Regards.
François-Xavier Guidet.

**Comment by timetheoretical** [comment]
Thanks to all of you for providing feedback!

With regards to special characters not being allowed, I think @gillesdubois is right in that this "problem" relates to Jitsi itself. I will add a note about this to the installation instructions, however.

Thanks @blinard-BIOINFO for providing that `.bat` script! I'll find a place to put it, either in the documentation or the installers folder, which may help others with deployment.

I agree that it would be better that the `x64` installer automatically targets the `Program Files` folder. I have a hunch that the VSTO plug-in itself is x86; the different installers may merely be needed to install different registry keys depending on the bitness of the office installation. I'll look into whether it is possible to change the default target directory per installer.

**Comment by timetheoretical** [comment]
I am closing this issue as the feature request has been fulfilled. If you would like to continue the conversations on default target directory for the installer and the treatment of special characters, please open separate issues.
