### ISSUE TITLE
Would it be possible to add a jitsi link in an existing "regular" meeting.

### ISSUE THREAD

**Issue by kieric82** [timetheoretical/jitsi-meet-outlook#22]
HI, 

Got an enhancement idea, it would be great if we could add the link or event better, a button "Join this meeting" in both the description and location of an existing meeting.

Thanks again for your work, much appreciated.

**Comment by kieric82** [comment]
I forgot, is it possible to set a password (random or not) in the link/config so the other end would receive the meeting invitation link and the password in the same invite?

Thank you!

**Comment by Extazx2** [comment]
@timetheoretical Do you know if that would be possible ?
My knowledge of add-ins isn't enough to know if this plugin can do both a new meeting and modify an existing meeting.

Microsoft Teams plugins is not doing this for example.

**Comment by kieric82** [comment]
Hi @Extazx2 

I'm using Teams on a daily basis and it is doing it. When you open a previously created meeting, you can click on the "Teams" button and it will insert a link in the description and "Teams meating" as the Location.

Thanks for the good work.

**Comment by timetheoretical** [comment]
> Got an enhancement idea, it would be great if we could add the link or event better, a button "Join this meeting" in both the description and location of an existing meeting.

It is at least possible to make the same ribbon appear in all appointments, including old "non-jitsi" appointments. However, I am not sure whether it is possible to make the ribbon change depending on whether an appointment contains a jitsi url or not. 

One solution could then be to add a jitsi link to existing appointments if the user clicks on the generate random id button. 

I made the ribbon only appear in appointments created from the "new jitsi meeting" button to avoid excessive cluttering of the interface. 

Do you think this would be a common use-case -- that people open pre-existing appointments to add a jitsi link?

> I forgot, is it possible to set a password (random or not) in the link/config so the other end would receive the meeting invitation link and the password in the same invite?

What I can remember from looking into this a while ago, it is not possible to pre-configure the password for a jitsi meeting, e.g. via the URL. It is the first user that enters the room who is given the authority to set the password for the room.

**Comment by kieric82** [comment]
> 
> 
> > Got an enhancement idea, it would be great if we could add the link or event better, a button "Join this meeting" in both the description and location of an existing meeting.
> 
> It is at least possible to make the same ribbon appear in all appointments, including old "non-jitsi" appointments. However, I am not sure whether it is possible to make the ribbon change depending on whether an appointment contains a jitsi url or not.
> 
> One solution could then be to add a jitsi link to existing appointments if the user clicks on the generate random id button.
> 
> I made the ribbon only appear in appointments created from the "new jitsi meeting" button to avoid excessive cluttering of the interface.
> 
> Do you think this would be a common use-case -- that people open pre-existing appointments to add a jitsi link?

I cant' speak for others, but personnally I would be using it everyday! :)
> 
> > I forgot, is it possible to set a password (random or not) in the link/config so the other end would receive the meeting invitation link and the password in the same invite?
> 
> What I can remember from looking into this a while ago, it is not possible to pre-configure the password for a jitsi meeting, e.g. via the URL. It is the first user that enters the room who is given the authority to set the password for the room.

Thank you very much for your work, I really appreciate it!

**Comment by gucci1977** [comment]
> I cant' speak for others, but personnally I would be using it everyday! :)
I would also use such a feature on daily basis to manage my meeting invitations.

**Comment by ChristianSteidle** [comment]
I would also use such a feature on daily basis to manage my meeting invitations.

**Comment by timetheoretical** [comment]
This was fixed in version 0.7.0, see #58.
