### ISSUE TITLE
Random ID button raises an exception when there is no Room ID in the message body

### ISSUE THREAD

**Issue by AlexandrePetit-Pas** [timetheoretical/jitsi-meet-outlook#26]
Hello,

An exception was raised when i manually deleted the Room ID and then tried to generate a new one by clicking on the "Random ID" button. 

In this case, the length of `oldValue` is 0 in the `setRoomId` method, so it cannot be replaced by `newValue`.

Here is the link to your code:
[https://github.com/timetheoretical/jitsi-meet-outlook/blob/master/JitsiMeetOutlook/AppointmentRibbonGroup.controls.cs#L35](url)

And here is a screenshot of the error: 
![jitsimeetoutlookbug](https://user-images.githubusercontent.com/15015082/85130681-af2a0980-b235-11ea-8353-1add774833d3.PNG)

A solution would be to replace the whole `appointmentItem.Body` if `oldValue.Length == 0` for example.

Thank you for your work !

**Comment by timetheoretical** [comment]
Thanks for the suggestion! That's indeed an issue that should be fixed, and could easily be so with your proposed solution. Will look into implementing this.

**Comment by timetheoretical** [comment]
This issue should now be resolved in the [v0.6.2](../releases/tag/v0.6.2) release.
