### ISSUE TITLE
No licence

### ISSUE THREAD

**Issue by gillesdubois** [timetheoretical/jitsi-meet-outlook#3]
Hi,

I think it would be nice to clarify the code's licence. 
I don't think there is any reference to a licence nor licence.md file.

Regards,
Gilles Dubois.

**Comment by timetheoretical** [comment]
Hi! Thanks for bringing up this issue. I've now added a licence.

**Comment by gillesdubois** [comment]
Hi @timetheoretical ,

Thanks for your reactivity :)
