### ISSUE TITLE
Create msi file

### ISSUE THREAD

**Issue by Extazx2** [timetheoretical/jitsi-meet-outlook#30]
Hello

I've made a different implementation with (for example) UUID to the rooms, and I would like to know how could I create the .msi file ?

**Comment by timetheoretical** [comment]
Hello, @Extazx2. I've used WiX Toolset 3.14 to create the .msi file. The toolset essentially reads in parameters that you set in an XML file (see `Product.wxs` in the `setup` folder), and creates the .msi accordingly. This is relying on a "Custom Action" that allows for parameters to be passed to the installer via cmd (see the `SettingsInstallerParameters` folder).

**Comment by Extazx2** [comment]
So, to create the msi, I should launch the command with all the parameters filled ?
Because I was trying with candle and light command but I was getting an error

**Comment by timetheoretical** [comment]
Well, I create it by right-clicking the setup project in Visual Studio, and then selecting "Build". Not sure what you mean by "candle and light command".

**Comment by Extazx2** [comment]
Ok, I think i've managed to alter some files in a way I couldn't build with wix.
I've cloned this repo this morning and I could see the "setup" folder as a wix "project" inside visual studio.

I'll come back here to update

**Comment by timetheoretical** [comment]
Sounds good. Note that you need to have WiX toolkit 3.14 installed as well (which I think is currently an "experimental" build; the 3.11 won't work).

**Comment by Extazx2** [comment]
Oh that's why then... I was using 3.11 !

**Comment by Extazx2** [comment]
I have another issue / question about certificate.

What kind of certificate did you use for this ?

Btw, my modifications included generating an UUID instead of a random string if you want a PR

**Comment by timetheoretical** [comment]
I didn't use a certificate, not sure if a self-signed certificate is automatically generated by WiX. That's why you get a message that the installer comes from an "untrusted" source, when you run it.

Which of the UUID fields were you thinking about?

**Comment by Extazx2** [comment]
I replaced the whole `generateRandomString(16)` with a  `generateUUID()`, to create rooms with uuid.
And i also added the `-` to the list of character accepted in filterLegalCharacters().
It follows my implementation of Jitsi though.

For the certificate, when I generate the JitsiMeetOutlook solution, it auto-toggle the "sign clickOnce manifest"
So I tought it signed with my test certificate.

Apparently I can install the .msi on another computer so it might be okay.

Thanks

**Comment by timetheoretical** [comment]
I see, well I'd always be interested to see a pull request, if you think it's a better implementation. 

What I liked with the `generateRandomString` function is that it is cryptographically secure, so each character in the string as an equal probability of occurring.

Please do PR the added "-" to `filterLegalCharacters` 🙂
