### ISSUE TITLE
Support for New Meeting Ribbon

### ISSUE THREAD

**Issue by telke** [timetheoretical/jitsi-meet-outlook#38]
After install, I noticed that it works great clicking the Jitsi button in the calendar view:
![image](https://user-images.githubusercontent.com/26144904/99407717-6b5b2f00-28bd-11eb-835c-76cee3f6bb77.png)

however, there is no JITSI button in the meeting ribbon as seen in the following picture:
![image](https://user-images.githubusercontent.com/26144904/99855055-fc4b3800-2b53-11eb-8fd6-0ace6fc51e15.png)

This might be the same issue #22  worded a different way.

-Craig-

**Comment by timetheoretical** [comment]
Hi @telke. Indeed it seems to be the same issue as #22. There have also been people asking for this on the jitsi forums, so I will look into having the button there in "non-jitsi" appointments too, when I get time.

By the way, you may want to edit out your personal email address in the second screen shot.

**Comment by timetheoretical** [comment]
This was fixed in version 0.7.0, see #58.
