### ISSUE TITLE
Need details/information about framework to regenerate

### ISSUE THREAD

**Issue by geraldvannier** [timetheoretical/jitsi-meet-outlook#42]
Hi, sorry to bother you with very basic questions but I have not found any information about my concern.
I'd like to test and  rebuild this project. I'm using VS Code... not sure this is what is required.
Could you tell me what dev framework tool/EDI is used for this projetc so I can install and work on it?

Thanks!
G.

**Comment by timetheoretical** [comment]
Hi, no worries.

To run the VSTO add on, you need to have [VSTO Runtime](https://www.microsoft.com/en-us/download/details.aspx?id=48217) installed.

To build it, I use [Visual Studio](https://visualstudio.microsoft.com/downloads/) (not VS Code). I think that takes care of downloading the project dependencies.

In addition, to build the installer, you need to have [WiX 3.14](https://wixtoolset.org/releases/development/) installed (doesn't work with lower versions).

Let me know if trying the above works for you. If so, I'll add it to the main project page.

**Comment by geraldvannier** [comment]
Thanks, project is loaded and ready to be modified! tooling is now good.
I can move to second second step (modify/rebuild/installer) ;)
