### ISSUE TITLE
RandomID

### ISSUE THREAD

**Issue by PatAgglo** [timetheoretical/jitsi-meet-outlook#6]
Hi!

This extenssion is verry good.

is it possible to generate a name that has no meaning?
For example: meet.jit.si/SJeo83lqp2ç 

Regards!

**Comment by timetheoretical** [comment]
Hi!

Glad to hear :)

I think this is a good idea. I may come back to this after addressing #2 and some of the points on the roadmap.

**Comment by jorgel272** [comment]
Any idea when the RandomID function will be in place? We have a project that can use your awesome plugin, but we need the RandomID function 👌🏼

If needed we are willing to sponsor you to make some time free!

Cheers!

**Comment by timetheoretical** [comment]
Thanks for the offer!

You can now find this function in release [v0.6.0](https://github.com/timetheoretical/jitsi-meet-outlook/releases/tag/v0.6.0).

**Comment by kieric82** [comment]
> Thank you very much for your work! I was hoping for that function! 👍 
> 
> Thanks for the offer!
> 
> You can now find this function in release [v0.6.0](https://github.com/timetheoretical/jitsi-meet-outlook/releases/tag/v0.6.0).

**Comment by jorgel272** [comment]
Wow that is really awesome! We’re going to test it 👌🏼

**Comment by PatAgglo** [comment]
Hi,

Thank You very much! It's perfect !!!

Regards
