### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by gillesdubois** [timetheoretical/jitsi-meet-outlook#7]
Hi @timetheoretical, 

I would like to implement translation capabilities in your product.
Most of my users are not really good when it come to english and i'm afraid i will loose most of them.
I saw a couple of way to do this and I'm not sure which one I need to use.

Did you already thinked about translation, if so, do you have an idea on what's the best wat to implement it ?

Atm, I just translated RC file by creating language specific files.

Regards,
Gilles Dubois.

**Comment by timetheoretical** [comment]
Hi @gillesdubois,

I have made an attempt at providing translations to the project. Essentially this solution is centered around a set of JSON files, each containing the label descriptions of all plug-in related buttons and labels, etc. in its own language. For example, I have provided [en.json](https://github.com/timetheoretical/jitsi-meet-outlook/blob/master/JitsiMeetOutlook/languages/en.json) which contains the descriptions in English.

The user then specifies what language they would like the plugin to appear in; the relevant JSON is then read into memory when the plugin launches.

Did you have any other solutions in mind?

If you agree with this approach, please submit a pull request wherein you have translated the `json` above and saved it as a separate file in the same folder, named `<ISO 639-1>.json` (see [ISO 639-1](https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes)).

I was thinking that the word lists from which the random room IDs are generated also could be added to this file eventually.

**Comment by gillesdubois** [comment]
Hi @timetheoretical, 

Ok I will send my PR asap with the French translation :)

If you want to translate your application you can use : https://www.transifex.com/
This product is free when you are an open-source product. It could bring you a lot more contributions if you have multiple translation.

I think having, ID name generations in this json will be appreciated. I can help you on this matter if you want.

Regards,
Gilles Dubois.

**Comment by timetheoretical** [comment]
The latest version has your translation implemented. :)

Unfortunately, I faced some issues with the old installer-compilation toolkit, so I had to spend some time learning another framework before this could be released.

Let me know if it works as expected and whether you wanted to make some more changes to the translation.

**Comment by gillesdubois** [comment]
Hi @timetheoretical,

Sorry for the late anwser, I will perform some test this week and make you a little feedback :)
Thanks for your hard work ! 

Regards,
Gilles Dubois.

**Comment by gillesdubois** [comment]
Hi @timetheoretical ,

I managed to install the new version on my computer this morning, it looks good so far.
Thus, I'm closing this issue.

Thanks again and don't hesitate to contact me if you need me to run some tests on your extensions.

Regards,
Gilles Dubois.

**Comment by timetheoretical** [comment]
Thanks a lot for your testing @gillesdubois!

Just to let you know, the random phrase generator can also now be translated by translating the lists within `roomNameGenerator` within [fr.json](JitsiMeetOutlook/languages/fr.json), if that is of interest.

The question there is whether special characters should be replaced before being added to the `.json` or whether the replacement should be done by adding some regex rules to the plug-in.

**Comment by gillesdubois** [comment]
Indeed, I will create a PR in a few days and try to translate these room names :)

Concerning the special characters, we could in the first place, use french words without any accents if that better for you, what do you think ?

**Comment by timetheoretical** [comment]
In a sense I would prefer to have as few dependencies as possible, and there is no diacritics-replacement package built-into C#.

However if more languages gets added further down the line, it would probably be more convenient to have some algorithm that replaces accents than needing to manually curate the word-lists. (This could also be a barrier for people contributing with more languages).

I may look into integrating a third-party package like [Diacritics.NET](https://github.com/thomasgalliker/Diacritics.NET). Will get back to you when I've tried!

**Comment by timetheoretical** [comment]
Okay, it seems like a robust package and an easy implementation. So it would be fine to include translations of the `pluralNoun`, `verb`, `adverb`, `adjective` lists in the `fr.json`, that include accents.

This could also be a solution to #11.

**Comment by gillesdubois** [comment]
Hi @timetheoretical, 

Thanks for your feedback, I will update the fr.json with pluralNoun and send a PR then :)

Regards,
Gilles Dubois.

**Comment by timetheoretical** [comment]
Perfect :)
